/**
 * Core pipeline logic shared between the CLI and the MCP server.
 * Handles cloning, analyzing, generating, committing, pushing, and PR creation.
 */

import os from 'os';
import fs from 'fs';
import path from 'path';
import simpleGit from 'simple-git';
import pLimit from 'p-limit';

import { fetchAllRepos, filterRepos, createPullRequest, mergePullRequest, getDefaultBranch } from './githubService.js';
import { analyzeRepo } from './repoAnalyzer.js';
import { generateReadme } from './readmeGenerator.js';

export const AI_BRANCH = 'ai/readme-update';
export const WORK_DIR = path.join(os.tmpdir(), 'readminator');

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Fetch and filter all repos eligible for README generation.
 * @param {object} config
 * @param {object} [filters={}]
 * @returns {Promise<object[]>} Eligible GitHub repo objects.
 */
export async function getEligibleRepos(config, filters = {}) {
  const allRepos = await fetchAllRepos(config.githubUsername, config.githubToken);
  return filterRepos(allRepos, config.githubToken, filters);
}

/**
 * Run the full pipeline for a single GitHub repo object.
 * Returns a result object rather than throwing so callers can decide how to handle errors.
 *
 * @param {object} repo - GitHub API repo object.
 * @param {object} config - READMInator config.
 * @param {object} provider - AI provider instance.
 * @param {object} [options={}]
 * @param {boolean} [options.dry=false] - Skip push/PR when true; returns readmeContent.
 * @param {boolean} [options.autoMerge=false] - Merge PR immediately after creation.
 * @param {function} [options.log] - Optional logging function (default: console.log).
 * @returns {Promise<PipelineResult>}
 *
 * @typedef {object} PipelineResult
 * @property {string}  repoName
 * @property {boolean} success
 * @property {string}  [readmeContent]  - Populated when options.dry is true.
 * @property {string}  [prUrl]          - GitHub PR URL (non-dry runs).
 * @property {boolean} [merged]         - Whether the PR was merged.
 * @property {string}  [error]          - Error message on failure.
 */
export async function processSingleRepo(repo, config, provider, options = {}) {
  const { dry = false, autoMerge = false, log = console.log } = options;
  const repoName = repo.name;
  const owner = repo.owner.login;
  const cloneDir = path.join(WORK_DIR, repoName);

  try {
    fs.mkdirSync(WORK_DIR, { recursive: true });

    // 1. Clone
    await cloneRepo(repo.clone_url, cloneDir, config.githubToken);
    log(`[${repoName}] Cloned.`);

    // 2. Analyze
    const summary = analyzeRepo(cloneDir, repoName);

    // 3. Generate README
    log(`[${repoName}] Generating README with ${config.provider}...`);
    const readmeContent = await generateReadme(provider, summary);

    // 4. Write README.md to disk
    fs.writeFileSync(path.join(cloneDir, 'README.md'), readmeContent, 'utf-8');
    log(`[${repoName}] README written.`);

    if (dry) {
      log(`[${repoName}] Dry run — skipping push & PR.`);
      return { repoName, success: true, readmeContent };
    }

    // 5. Git: branch → commit → push
    const git = simpleGit(cloneDir);
    const defaultBranch = await getDefaultBranch(owner, repoName, config.githubToken);

    const branchList = await git.branchLocal();
    if (branchList.all.includes(AI_BRANCH)) {
      await git.deleteLocalBranch(AI_BRANCH, true);
    }

    await git.checkoutLocalBranch(AI_BRANCH);
    await git.add('README.md');
    await git.commit('docs: add AI-generated README.md [readminator]');

    const remote = buildAuthenticatedUrl(repo.clone_url, config.githubToken);
    await git.push(remote, AI_BRANCH, ['--force']);
    log(`[${repoName}] Pushed branch ${AI_BRANCH}.`);

    // 6. Create PR
    const pr = await createPullRequest(owner, repoName, config.githubToken, {
      title: 'docs: AI-generated README.md',
      body: [
        '## AI-Generated README',
        '',
        'This pull request was automatically created by **READMInator**.',
        '',
        'The README was generated by analyzing the repository structure, dependencies, and entry-point files.',
        '',
        '> Please review, edit as needed, and merge if satisfied.',
      ].join('\n'),
      head: AI_BRANCH,
      base: defaultBranch,
    });
    log(`[${repoName}] PR created: ${pr.html_url}`);

    // 7. Optional: merge
    let merged = false;
    if (autoMerge) {
      try {
        await mergePullRequest(owner, repoName, pr.number, config.githubToken);
        merged = true;
        log(`[${repoName}] PR merged.`);
      } catch (mergeErr) {
        log(`[${repoName}] Auto-merge failed (PR left open): ${mergeErr.message}`);
      }
    }

    return { repoName, success: true, prUrl: pr.html_url, merged };
  } catch (err) {
    return { repoName, success: false, error: err.message };
  } finally {
    cleanupDir(cloneDir);
  }
}

/**
 * Run the full pipeline for all eligible repos with concurrency control.
 * @param {object} config
 * @param {object} provider
 * @param {object} [filters={}]
 * @param {object} [options={}]
 * @param {boolean} [options.dry=false]
 * @param {boolean} [options.autoMerge=false]
 * @param {number}  [options.concurrency=3]
 * @param {function} [options.log]
 * @returns {Promise<{ success: PipelineResult[], failed: PipelineResult[] }>}
 */
export async function processAllRepos(config, provider, filters = {}, options = {}) {
  const { concurrency = 3, log = console.log } = options;

  const eligible = await getEligibleRepos(config, filters);
  log(`${eligible.length} repos eligible for README generation.`);

  if (eligible.length === 0) {
    return { success: [], failed: [] };
  }

  const limit = pLimit(concurrency);
  const results = await Promise.all(
    eligible.map((repo) =>
      limit(() => processSingleRepo(repo, config, provider, options))
    )
  );

  return {
    success: results.filter((r) => r.success),
    failed: results.filter((r) => !r.success),
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

async function cloneRepo(cloneUrl, destDir, token) {
  cleanupDir(destDir);
  const git = simpleGit();
  await git.clone(buildAuthenticatedUrl(cloneUrl, token), destDir, ['--depth', '1']);
}

function buildAuthenticatedUrl(cloneUrl, token) {
  return cloneUrl.replace('https://', `https://${token}@`);
}

function cleanupDir(dirPath) {
  if (fs.existsSync(dirPath)) {
    fs.rmSync(dirPath, { recursive: true, force: true });
  }
}
